[2025-04-03T09:16:04.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T09:16:04.266+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_name.create_table_intermediaire manual__2025-04-03T09:15:58.962508+00:00 [queued]>
[2025-04-03T09:16:04.279+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_name.create_table_intermediaire manual__2025-04-03T09:15:58.962508+00:00 [queued]>
[2025-04-03T09:16:04.279+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-03T09:16:04.301+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryCreateTableOperator): create_table_intermediaire> on 2025-04-03 09:15:58.962508+00:00
[2025-04-03T09:16:04.315+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-03T09:16:04.318+0000] {standard_task_runner.py:72} INFO - Started process 455 to run task
[2025-04-03T09:16:04.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag_name', 'create_table_intermediaire', 'manual__2025-04-03T09:15:58.962508+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/intermediaire_table.py', '--cfg-path', '/tmp/tmpv0_f7cng']
[2025-04-03T09:16:04.323+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask create_table_intermediaire
[2025-04-03T09:16:04.404+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag_name.create_table_intermediaire manual__2025-04-03T09:15:58.962508+00:00 [running]> on host d6badcb20287
[2025-04-03T09:16:04.563+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag_name' AIRFLOW_CTX_TASK_ID='create_table_intermediaire' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T09:15:58.962508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T09:15:58.962508+00:00'
[2025-04-03T09:16:04.566+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-03T09:16:04.567+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-03T09:16:04.567+0000] {logging_mixin.py:190} INFO - Current task name:create_table_intermediaire state:running start_date:2025-04-03 09:16:04.266718+00:00
[2025-04-03T09:16:04.567+0000] {logging_mixin.py:190} INFO - Dag name:my_dag_name and current dag run status:running
[2025-04-03T09:16:04.568+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T09:16:04.596+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1257, in execute
    bq_hook = BigQueryHook(
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 162, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 283, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `gcp_co` isn't defined
[2025-04-03T09:16:04.610+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-03T09:16:04.611+0000] {logging_mixin.py:190} INFO - Task start:2025-04-03 09:16:04.266718+00:00 end:2025-04-03 09:16:04.610077+00:00 duration:0.343359
[2025-04-03T09:16:04.612+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryCreateTableOperator): create_table_intermediaire> dag:<DAG: my_dag_name> dagrun:<DagRun my_dag_name @ 2025-04-03 09:15:58.962508+00:00: manual__2025-04-03T09:15:58.962508+00:00, state:running, queued_at: 2025-04-03 09:15:58.977247+00:00. externally triggered: True>
[2025-04-03T09:16:04.612+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `gcp_co` isn't defined
[2025-04-03T09:16:04.612+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=my_dag_name, task_id=create_table_intermediaire, run_id=manual__2025-04-03T09:15:58.962508+00:00, execution_date=20250403T091558, start_date=20250403T091604, end_date=20250403T091604
[2025-04-03T09:16:04.656+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T09:16:04.657+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task create_table_intermediaire (The conn_id `gcp_co` isn't defined; 455)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1257, in execute
    bq_hook = BigQueryHook(
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 162, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 283, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `gcp_co` isn't defined
[2025-04-03T09:16:04.699+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-03T09:16:04.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
