[2025-04-03T09:16:04.267+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T09:16:04.291+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T09:15:58.962508+00:00 [queued]>
[2025-04-03T09:16:04.303+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T09:15:58.962508+00:00 [queued]>
[2025-04-03T09:16:04.304+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-03T09:16:04.325+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_xcom_data> on 2025-04-03 09:15:58.962508+00:00
[2025-04-03T09:16:04.339+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-03T09:16:04.343+0000] {standard_task_runner.py:72} INFO - Started process 457 to run task
[2025-04-03T09:16:04.346+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag_name', 'fetch_xcom_data', 'manual__2025-04-03T09:15:58.962508+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/intermediaire_table.py', '--cfg-path', '/tmp/tmpzll4825v']
[2025-04-03T09:16:04.349+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask fetch_xcom_data
[2025-04-03T09:16:04.428+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T09:15:58.962508+00:00 [running]> on host d6badcb20287
[2025-04-03T09:16:04.570+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag_name' AIRFLOW_CTX_TASK_ID='fetch_xcom_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T09:15:58.962508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T09:15:58.962508+00:00'
[2025-04-03T09:16:04.573+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-03T09:16:04.573+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-03T09:16:04.574+0000] {logging_mixin.py:190} INFO - Current task name:fetch_xcom_data state:running start_date:2025-04-03 09:16:04.292338+00:00
[2025-04-03T09:16:04.574+0000] {logging_mixin.py:190} INFO - Dag name:my_dag_name and current dag run status:running
[2025-04-03T09:16:04.574+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T09:16:04.590+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/intermediaire_table.py", line 86, in fetch_xcom_data
    result1 = ti.xcom_pull(task_ids='call_external_function')[0]  # Récupère le premier résultat
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2025-04-03T09:16:04.609+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-03T09:16:04.610+0000] {logging_mixin.py:190} INFO - Task start:2025-04-03 09:16:04.292338+00:00 end:2025-04-03 09:16:04.608929+00:00 duration:0.316591
[2025-04-03T09:16:04.610+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_xcom_data> dag:<DAG: my_dag_name> dagrun:<DagRun my_dag_name @ 2025-04-03 09:15:58.962508+00:00: manual__2025-04-03T09:15:58.962508+00:00, state:running, queued_at: 2025-04-03 09:15:58.977247+00:00. externally triggered: True>
[2025-04-03T09:16:04.611+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not subscriptable
[2025-04-03T09:16:04.611+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=my_dag_name, task_id=fetch_xcom_data, run_id=manual__2025-04-03T09:15:58.962508+00:00, execution_date=20250403T091558, start_date=20250403T091604, end_date=20250403T091604
[2025-04-03T09:16:04.657+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T09:16:04.658+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task fetch_xcom_data ('NoneType' object is not subscriptable; 457)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/intermediaire_table.py", line 86, in fetch_xcom_data
    result1 = ti.xcom_pull(task_ids='call_external_function')[0]  # Récupère le premier résultat
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2025-04-03T09:16:04.681+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-03T09:16:04.730+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-03T09:16:04.737+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
